[package]
name = "crate-root"
version = "0.1.0"
authors = ["Jason Klein <jason@jasonklein.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
